-- Script para verificar y crear las tablas categoria y marcas con datos
-- Ejecuta este script en el SQL Editor de Supabase

-- 1. Verificar si las tablas existen
SELECT 'Verificando tablas existentes:' as info;
SELECT table_name FROM information_schema.tables 
WHERE table_schema = 'public' AND table_name IN ('categoria', 'marcas');

-- 2. Crear tabla categoria si no existe
CREATE TABLE IF NOT EXISTS categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    descripcion TEXT,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

-- 3. Crear tabla marcas si no existe
CREATE TABLE IF NOT EXISTS marcas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    descripcion TEXT,
    CONSTRAINT marcas_pkey PRIMARY KEY (id)
);

-- 4. Verificar datos existentes
SELECT 'Datos en categoria:' as info;
SELECT COUNT(*) as total_categorias FROM categoria;

SELECT 'Datos en marcas:' as info;
SELECT COUNT(*) as total_marcas FROM marcas;

-- 5. Insertar datos de ejemplo si las tablas están vacías
INSERT INTO categoria (descripcion) 
SELECT * FROM (VALUES 
    ('Lavarropas'),
    ('Heladeras'),
    ('Cocinas'),
    ('Microondas'),
    ('Aire Acondicionado'),
    ('Televisores'),
    ('Computadoras'),
    ('Celulares')
) AS v(descripcion)
WHERE NOT EXISTS (SELECT 1 FROM categoria);

INSERT INTO marcas (descripcion) 
SELECT * FROM (VALUES 
    ('Whirlpool'),
    ('Samsung'),
    ('LG'),
    ('Philips'),
    ('Panasonic'),
    ('Sony'),
    ('Apple'),
    ('Dell'),
    ('HP'),
    ('Motorola')
) AS v(descripcion)
WHERE NOT EXISTS (SELECT 1 FROM marcas);

-- 6. Verificar datos finales
SELECT 'Categorías finales:' as info;
SELECT id, descripcion FROM categoria ORDER BY id;

SELECT 'Marcas finales:' as info;
SELECT id, descripcion FROM marcas ORDER BY id; 