-- Script simplificado para crear la tabla productos_planes_default
-- Ejecuta este script en el SQL Editor de Supabase

-- Crear tabla productos_planes_default si no existe
CREATE TABLE IF NOT EXISTS productos_planes_default (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fk_id_producto BIGINT NOT NULL,
    fk_id_plan BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT productos_planes_default_pkey PRIMARY KEY (id)
);

-- Crear índices básicos
CREATE INDEX IF NOT EXISTS productos_planes_default_fk_id_producto_idx ON productos_planes_default USING btree (fk_id_producto);
CREATE INDEX IF NOT EXISTS productos_planes_default_fk_id_plan_idx ON productos_planes_default USING btree (fk_id_plan);

-- Verificar que la tabla se creó correctamente
SELECT 'Tabla productos_planes_default creada:' as info;
SELECT COUNT(*) as total_registros FROM productos_planes_default;

-- Mostrar la estructura de la tabla
SELECT 'Estructura de la tabla:' as info;
SELECT column_name, data_type, is_nullable
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name = 'productos_planes_default'
ORDER BY ordinal_position;
