-- Crear tabla productos_planes_default si no existe
CREATE TABLE IF NOT EXISTS productos_planes_default (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fk_id_producto BIGINT NOT NULL,
    fk_id_plan BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT productos_planes_default_pkey PRIMARY KEY (id),
    CONSTRAINT productos_planes_default_fk_id_producto_fkey FOREIGN KEY (fk_id_producto) REFERENCES productos(id) ON DELETE CASCADE,
    CONSTRAINT productos_planes_default_fk_id_plan_fkey FOREIGN KEY (fk_id_plan) REFERENCES planes_financiacion(id) ON DELETE CASCADE,
    CONSTRAINT productos_planes_default_unique UNIQUE (fk_id_producto, fk_id_plan)
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS productos_planes_default_fk_id_producto_idx ON productos_planes_default USING btree (fk_id_producto);
CREATE INDEX IF NOT EXISTS productos_planes_default_fk_id_plan_idx ON productos_planes_default USING btree (fk_id_plan);
CREATE INDEX IF NOT EXISTS productos_planes_default_activo_idx ON productos_planes_default USING btree (activo);

-- Crear trigger para llenar automáticamente la tabla cuando se crea un nuevo producto
CREATE OR REPLACE FUNCTION insert_default_financing_plans()
RETURNS TRIGGER AS $$
BEGIN
    -- Insertar el nuevo producto con todos los planes de financiación activos
    INSERT INTO productos_planes_default (fk_id_producto, fk_id_plan, activo)
    SELECT 
        NEW.id as fk_id_producto,
        pf.id as fk_id_plan,
        true as activo
    FROM planes_financiacion pf
    WHERE pf.activo = true
    ON CONFLICT (fk_id_producto, fk_id_plan) DO NOTHING;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Crear el trigger
DROP TRIGGER IF EXISTS trigger_insert_default_financing_plans ON productos;
CREATE TRIGGER trigger_insert_default_financing_plans
    AFTER INSERT ON productos
    FOR EACH ROW
    EXECUTE FUNCTION insert_default_financing_plans();

-- Comentarios sobre la tabla
COMMENT ON TABLE productos_planes_default IS 'Tabla que asocia todos los productos con todos los planes de financiación por defecto';
COMMENT ON COLUMN productos_planes_default.fk_id_producto IS 'ID del producto';
COMMENT ON COLUMN productos_planes_default.fk_id_plan IS 'ID del plan de financiación';
COMMENT ON COLUMN productos_planes_default.activo IS 'Indica si la asociación está activa';
