-- Crear tabla categoria (singular)
CREATE TABLE IF NOT EXISTS categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    nombre VARCHAR(100),
    descripcion TEXT,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

-- Insertar datos de ejemplo para categorías
INSERT INTO categoria (nombre, descripcion) VALUES
('Lavarropas', 'Lavarropas automáticos y semiautomáticos'),
('Heladeras', 'Heladeras y freezers'),
('Cocinas', 'Cocinas y hornos'),
('Microondas', 'Microondas y hornos eléctricos'),
('Aire Acondicionado', 'Aires acondicionados split y portátiles')
ON CONFLICT (nombre) DO NOTHING; 