-- Script para crear las tablas categoria y marcas con datos
-- Ejecuta este script completo en el SQL Editor de Supabase

-- 1. Crear tabla categoria
CREATE TABLE IF NOT EXISTS categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    descripcion TEXT,
    CONSTRAINT categoria_pkey PRIMARY KEY (id)
);

-- 2. Crear tabla marcas
CREATE TABLE IF NOT EXISTS marcas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    descripcion TEXT,
    CONSTRAINT marcas_pkey PRIMARY KEY (id)
);

-- 3. Limpiar datos existentes (opcional)
DELETE FROM categoria;
DELETE FROM marcas;

-- 4. Insertar categorías
INSERT INTO categoria (descripcion) VALUES
('Lavarropas'),
('Heladeras'),
('Cocinas'),
('Microondas'),
('Aire Acondicionado'),
('Televisores'),
('Computadoras'),
('Celulares');

-- 5. Insertar marcas
INSERT INTO marcas (descripcion) VALUES
('Whirlpool'),
('Samsung'),
('LG'),
('Philips'),
('Panasonic'),
('Sony'),
('Apple'),
('Dell'),
('HP'),
('Motorola');

-- 6. Verificar que se insertaron los datos
SELECT 'Categorías creadas:' as info;
SELECT id, descripcion FROM categoria ORDER BY id;

SELECT 'Marcas creadas:' as info;
SELECT id, descripcion FROM marcas ORDER BY id; 